# %%
import jax.numpy as jnp
from jax import random
from jax.scipy.stats import norm
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
import numpyro.distributions as dist
from numpyro.distributions import constraints
from tensorflow_probability.substrates import jax as tfp
import jax.scipy.special as jss
from BI import bi

# Core parameters
n = 1000
spearman_rho = 0.6
pearson_rho = 2 * np.sin((np.pi / 6) * spearman_rho)

# Covariance matrix for bivariate standard normal
Sigma = jnp.array(
    [[1.0**2, pearson_rho * 1.0 * 1.0], [pearson_rho * 1.0 * 1.0, 1.0**2]]
)
mu = jnp.array([0.0, 0.0])
Sigma_chol = jnp.linalg.cholesky(Sigma)

seed = 123
rng_key = random.PRNGKey(seed)

# Marginal parameters (Beta and Poisson)
alpha_param, beta_param = 2.0, 5.0
lambda_param = 3.0


# %%
# -------------------------------------------------------------------
# 1. Raw Functional Approach
# -------------------------------------------------------------------
samples_normal = random.multivariate_normal(rng_key, mean=mu, cov=Sigma, shape=(n,))
samples_uniform = norm.cdf(samples_normal)

u1 = np.asarray(samples_uniform[:, 0])
u2 = np.asarray(samples_uniform[:, 1])

x_beta = stats.beta.ppf(u1, a=alpha_param, b=beta_param)
x_poisson = stats.poisson.ppf(u2, mu=lambda_param)

# -------------------------------------------------------------------
# 2. Built-in Copula (Beta & Poisson) with BI
# -------------------------------------------------------------------
m = bi("cpu")


class BetaPoissonMarginal(dist.Distribution):
    """
    A custom marginal distribution wrapper combining Beta and Poisson distributions.

    This class bypasses NumPyro's constraint that multivariate copula marginals
    must belong to the exact same distribution family. By grouping both variables into
    a single vector space of size 2, it allows the Gaussian copula to map the first
    latent dimension to a Beta distribution and the second dimension to a Poisson distribution.
    """

    # The support is a continuous unbounded vector during HMC sampling for the latent space
    support = constraints.real_vector

    def __init__(self, alpha, beta, lam, validate_args=None):
        """
        Initializes the custom marginal joint distribution.

        Args:
            alpha: Shape parameter (alpha) for the first variable (Beta).
            beta: Shape parameter (beta) for the first variable (Beta).
            lam: Rate parameter (lambda) for the second variable (Poisson).
            validate_args: Verification flag for NumPyro's distribution base class.
        """
        self.alpha = alpha
        self.beta = beta
        self.lam = lam
        # batch_shape=(2,) tells NumPyro that this distribution evaluates two independent
        # variables simultaneously per sample. event_shape=() means each evaluates to a scalar.
        super().__init__(batch_shape=(2,), event_shape=(), validate_args=validate_args)

    def log_prob(self, value):
        """
        Computes the log probability density (or mass) for the observations.

        This is called during inference (HMC/NUTS) to compute the likelihood of the model.
        """
        # value[..., 0] contains the observations/samples for the Beta variable
        v1 = value[..., 0]
        # value[..., 1] contains the observations/samples for the Poisson variable
        v2 = value[..., 1]

        # Calculate individual log probabilities using their respective NumPyro distributions
        lp1 = dist.Beta(self.alpha, self.beta).log_prob(v1)
        lp2 = dist.Poisson(self.lam).log_prob(v2)

        # Stack the log probabilities back into the shape expected by the copula (..., 2)
        return jnp.stack([lp1, lp2], axis=-1)

    def cdf(self, value):
        """
        Computes the Cumulative Distribution Function (CDF) for mapping.

        This function transforms the observed data back into uniform probabilities [0, 1]
        during inference, allowing the copula to link them to the latent Gaussian space.
        """
        v1 = value[..., 0]
        v2 = value[..., 1]

        # Use TensorFlow Probability's Regularized Incomplete Beta function (betainc)
        # because it supports JAX autodiff (gradients) with respect to alpha and beta parameters.
        cdf1 = tfp.math.betainc(self.alpha, self.beta, v1)

        # JAX's regularized upper incomplete gamma function (gammaincc) is used as an
        # alternative to compute the Poisson CDF. Floor is used to step-function continuous inputs.
        # P(X <= k) = Q(k+1, lambda) = gammaincc(k+1, lambda)
        cdf2 = jss.gammaincc(jnp.floor(v2) + 1.0, self.lam)

        return jnp.stack([cdf1, cdf2], axis=-1)

    def icdf(self, u):
        """
        Computes the Inverse Cumulative Distribution Function (Quantile function).

        This is used for forward sampling (generating new data from the model).
        It transforms standard uniform values u ~ U[0, 1] generated by the copula
        into the original target scales (Beta and Poisson).
        """
        import numpy as np
        import scipy.stats as stats

        # Scipy operates on CPU NumPy arrays, so we must coerce JAX arrays safely
        u1 = np.asarray(u[..., 0])
        u2 = np.asarray(u[..., 1])

        # Apply the Scipy Point Percentile Function (ppf/icdf) for Beta and Poisson
        x_b = stats.beta.ppf(u1, a=np.asarray(self.alpha), b=np.asarray(self.beta))
        x_p = stats.poisson.ppf(u2, mu=np.asarray(self.lam))

        # Coerce back to JAX arrays to integrate into the regular BI/JAX pipeline properly
        return jnp.stack([jnp.array(x_b), jnp.array(x_p)], axis=-1)


samples_bi = m.dist.gaussian_copula(
    marginal_dist=BetaPoissonMarginal(alpha_param, beta_param, lambda_param),
    correlation_cholesky=Sigma_chol,
    sample=True,
    shape=(n,),
    seed=seed,
)
x_b1 = samples_bi[:, 0]
x_b2 = samples_bi[:, 1]
