# Measuring error
## General Principles
Measurement error refers to the variability in the measurement of a variable, and measurement error can be generated by several factors, such as sampling bias, censoring bias, and group size heterogeneity. It is an important consideration in many fields, including statistics, economics, and engineering, where accurate measurements are crucial for making informed decisions. To account for measurement error, we can use a _measurement error model_. This model assumes that the measurement of a variable is subject to an error, which can be modeled using a probability distribution. The model can be used to estimate the parameters of the measurement error distribution, such as the mean and variance, and to make predictions about the measurements based on the estimated parameters. Measurement error models are _composed models_ (i.e., models with sub-models) that evaluate different generative processes, starting with the measurement error process, which is then used to generate the observed data.


## Example
Below is an example code snippet demonstrating a Bayesian measurement error model using the Bayesian Inference (BI) package. The data consist of three continuous variables (marriage rate, divorce rate, age), and the goal is to estimate the effect of age and marriage rate on the divorce rate while considering that the divorce rate has a measurement error.

::: {.panel-tabset group="language"}
## Python
``` python
from BI import bi

# Setup device------------------------------------------------
m = bi(platform='cpu')

# Import Data & Data Manipulation ------------------------------------------------
# Import
from importlib.resources import files
data_path = files('BI.resources.data') / 'WaffleDivorce.csv'
m.data(data_path, sep=';') 
m.scale(['Divorce', 'Divorce SE', 'MedianAgeMarriage']) # Scale
dat = dict(
    D_obs = jnp.array(m.df['Divorce'].values),   
    D_sd = jnp.array(m.df['Divorce'].values), 
    A = jnp.array(m.df['MedianAgeMarriage'].values), 
    N = m.df.shape[0]   
)
m.data_on_model = dat # Send to model (convert to jax array)


# Define model ------------------------------------------------
def model(D_obs, D_sd, A, N):  
    a = m.dist.normal(0, 0.2, name = 'a') 
    bA = m.dist.normal(0, 0.5, name = 'bA') 
    s = m.dist.exponential(1, name = 's') 
    mu = a + bA * A + bM * M
    D_true = m.dist.normal(mu, s, name = 'D_true') 
    m.normal(D_true , D_sd, obs = D_obs) 

# Run MCMC ------------------------------------------------
m.fit(model)  # Optimize model parameters through MCMC sampling

# Summary ------------------------------------------------
m.summary() # Get posterior distributions
```

``` R
```
:::

## Mathematical Details
### *Bayesian formulation*

$$
D_i^* \sim Normal(D_i, \sigma_i)
$$

$$
D_i \sim Normal(\mu_i, \sigma)
$$

$$
\mu_i = \alpha + \beta_A A_i + \beta_M M_i 
$$

$$
\sigma \sim Normal(1)
$$

where:

- $D_i^*$ is the observed divorce rate.

- $D_i$ is the true divorce rate.

- $\mu_i$ is the mean of the true divorce rate.

- $\sigma$ is the standard deviation of the true divorce rate.

- $\alpha$ is the intercept term.

- $\beta_A$ is the regression coefficient for age.

- $\beta_M$ is the regression coefficient for marriage rate.    


## Notes
::: callout-note
This is an approach that can be extended to any kind of model previously described. For example, one could generate a Bernoulli measurement error model by generating a process for the probabilities of success and failure. We can even go further by potentially having an error rate that is present only in one of the two outcomes.


:::

## Reference(s)

@mcelreath2018statistical