# 17. Modeling Network

A network represents the relationships (links) between entities (nodes). These links can be weighted (weighted network) or unweighted (binary network), directed (directed network) or undirected (undirected network). Regardless of their type, networks generate links shared by nodes, leading to data dependency when modeling the network. One proposed solution is to model network links with random [intercepts](12.%20Varying%20intercepts.qmd) and [effects](13.%20Varying%20slopes.qmd). By adding such parameters to the model, we can account for the correlations between node link relationships. The particularity here is that random intercepts and effects are generated for both [nodal effects 🛈](19. %20Network%20model.qmd "nodal categorical (e.g., sex) or continuous (e.g., age) characteristics") and [dyadic effects 🛈](19.%20Network%20model.qmd " link-related categorical (e.g., same group membership) or continuous (e.g., genetic distances) characteristics between nodes"). For nodal characteristics, the random intercepts and effects are identical to those described in previous chapters and will therefore not be detailed further.

When modeling network data, the relationships between nodes can be represented by weighted links. These weights might indicate the strength of connections such as the number of interactions, shared attributes, or other quantitative measures of connection strength between nodes. However, in such cases as links are shared between nodes we obtain data dependency and to account for such data structure we need to account for it. One proposed solution is to generate random intercepts and effects. Indeed, by adding such parameter in our model we can account for correlation between

The simple model that can be built to model link weights between nodes *i* and *j* can be defined as follows:

$$
G_{ij} \sim Poisson(Y_{ij}) \\
log(Y_{ij}) =  \alpha  + \lambda_i + \pi_j + \delta_{ij}
$$

where: - ( Y\_{ij} ) is the weight of links between *i* and *j*. - ( \alpha ) is the intercept. - ( \lambda\_i ) is the characteristic of node *i* that affects node *i*'s propensity to emit a link toward node *j*. - ( \pi*j ) is the characteristic of node j\* that affects node *j*'s propensity to receive a link from node *i*. - ( \delta{ij} ) is a matrix of dyadic effects governing reciprocity between dyads.

Note that any additional covariates can be added with a regression coefficient to the model representing nodal characteristics (e.g., sex, age) or dyadic characteristics (e.g., genetic distances).

To account for correlation between the propensity to emit and receive links of a dyad, we can use [varying slopes](13.%20Varying%20slopes.md) as follows:

$$
\left(\begin{array}{cc} 
\lambda_i \\
\pi_j 
\end{array}\right) 
\sim 
MultivariateNormal\left(\begin{array}{cc} 
\left(\begin{array}{cc} 
0 \\
0
\end{array}\right),
\left(\begin{array}{cc} 
\sigma_\lambda^2 & \sigma_\pi \sigma_{\lambda \rho }\\
\sigma_\lambda \sigma_{\pi \rho } & \sigma_\pi^2
\end{array}\right)
\end{array}\right)
$$

This can be optimized for computation by:

$$
\left(\begin{array}{cc} 
\lambda_i \\
\pi_j 
\end{array}\right) 
\sim 
MultivariateNormal\left(\begin{array}{cc} 
\left(\begin{array}{cc} 
\sigma_\lambda \\
\sigma_\pi
\end{array}\right) \circ 
\left(\begin{array}{cc} 
L *
\left(\begin{array}{cc} 
\hat{\lambda}_i \\ \hat{\pi}_i
\end{array}\right)
\end{array}\right)
\end{array}\right)
$$

$$
\sigma_\alpha \sim Exponential(1)
$$

$$
\sigma_\pi \sim Exponential(1)
$$

$$
L \sim LKJ(2)
$$

Similarly, the dyad reciprocity effect is also modeled using a random slope:

$$
\left(\begin{array}{cc} 
\delta_{ij} \\
\delta_{ji}
\end{array}\right) 
\sim 
MultivariateNormal\left(\begin{array}{cc} 
\left(\begin{array}{cc} 
\sigma_\delta \\
\sigma_\delta
\end{array}\right) \circ 
\left(\begin{array}{cc} 
L_\delta *
\left(\begin{array}{cc} 
\hat{\delta}_{ij} \\ \hat{\delta}_{ji}
\end{array}\right)
\end{array}\right)
\end{array}\right)
$$

## Conciderations

-   Network links can be modeled using Bernoulli, Binomial, Poisson, or zero-inflated Poisson distributions. So, by replacing the Poisson distribution with a binomial distribution, we can model the existence or absence of link weights — i.e., model binary networks.

-   Note that if the network is undirected, then accounting for correlation between propensity to emit and receive links is not necessary, and the terms ( \lambda\_i ), ( \pi*j ), and (\* \delta{ij} ) are no longer required. (Is it correct?)

-   In the following chapters, we will see how to incorporate additional network effects into the model to account for network structural properties (e.g., clusters, assortativity, triadic closure, etc.).

# Notes

-   We can apply multiple variables similarly as [chapter 2: Multiple continuous Variables](2.%20Multiple%20continuous%20Variables.qmd).

-   We can apply interaction terms similarly as [chapter 3: Interaction between continuous variables](3.%20Interaction%20between%20continuous%20variables.qmd).